### ISSUE TITLE
Game intro

### ISSUE THREAD

**Issue by cole-ifthisusernameistakenimgoingtocry** [Cyco12/LudumDare42#8]
the intro for the game, that will lead to the main menu. It could start with the user seeing an interactive fake windows 95 desktop (obviously it won't need to have many features since it's not the main part of the game) for about 10 seconds, then they get an error message saying the computer is out of space. the error will have a "fix problems" option, which will take the player to the main menu.

**Comment by Cyco12** [comment]
Added in fa8409cb87baeec58e217e49d53be7347a60df34
