### ISSUE TITLE
Game over menu (win/lose)

### ISSUE THREAD

**Issue by cole-ifthisusernameistakenimgoingtocry** [Cyco12/LudumDare42#9]
If the player loses, the end screen could look like a system crash (blue screen of death), and will say "press any key to reboot". doing so will take the player back to the main menu.

If the player wins, they get another windows message telling them how much space they freed up (score, possibly leaderboard)

**Comment by Cyco12** [comment]
Completed in 1169bb5b4347953933ec1c3dbda39ef412a25d11
